application: crowd-sourcing-report
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries: 
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: matplotlib
  version: latest
- name: pycrypto
  version: latest


handlers:
- url: /.*
  script: homepage.application
- url: /Content
  static_dir: Content
